[book]
authors = ["Young-Gi Park"]
language = "ko"
src = "src"
title = "mdbook-boilerplate"

[build]
build-dir = "book"
create-missing = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.autosummary]
index-name = "index.md"
ignore-hidden = true

[preprocessor.links]
after = ["autosummary"]

[preprocessor.toc] 
after = ["autosummary"]
max-level = 2

[output]

[output.html]
#additional-css = ["theme/vitepress.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# Disable rustdoc tests for documentation
[output.html.playground]
runnable = false
