[book]
authors = ["Young-Gi Park"]
language = "en"
src = "src"
title = "test"

[build]
build-dir = "book"
create-missing = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.autosummary]
# index 파일의 이름 지정 (기본값: "index.md")
index-name = "index.md"

# 숨김 파일 무시 여부 (기본값: true)
# .으로 시작하는 파일이나 _로 시작하는 파일 무시
ignore-hidden = true

# 다른 전처리기보다 먼저 실행되도록 설정
[preprocessor.links]
after = ["autosummary"]

[preprocessor.toc] 
after = ["autosummary"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# Disable rustdoc tests for documentation
[output.html.playground]
runnable = false
